AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-flask -   Sample SAM Template for lambda-flask with AWS Lambda Powertools

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  FlaskrApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - image/x-icon
        - image/png
        - image/jpeg
        - audio/mpeg
        - application/octet-stream
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./swagger.yaml

  FlaskrFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: flaskr/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        RootPath:
          Type: Api
          Properties:
            RestApiId: !Ref FlaskrApi
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            RestApiId: !Ref FlaskrApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  FlaskrApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${FlaskrApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FlaskrFunction:
    Description: Lambda Function ARN
    Value: !GetAtt FlaskrFunction.Arn
  FlaskrFunctionIamRole:
    Description: Implicit IAM Role created for the function
    Value: !GetAtt FlaskrFunctionRole.Arn
